language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/demo-all-nodes.cpp PLATFORMIO_CI_EXTRA_ARGS="--board=d1_mini"

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --project-conf=platformio.ini
