language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/demo-sensor-nodes.cpp
    - PLATFORMIO_CI_SRC=examples/demo-relay-contact-nodes.cpp
    - PLATFORMIO_CI_SRC=examples/demo-pulse-node.cpp
    - PLATFORMIO_CI_SRC=examples/demo-ping-node.cpp

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --project-conf=platformio.ini
